### ISSUE TITLE
求帮助,WIN10下jackc main.jack报错main.jack isn't a directory

### ISSUE THREAD

**Issue by yjj2002** [Xiang1993/C-Mini-Compiler#12]

**Comment by wanwang2** [comment]
蛤？你可以把他的文档看一遍，少什么东西------------------ 原始邮件 ------------------
发件人: "yjj2002"<notifications@github.com>
发送时间: 2019年7月12日(星期五) 晚上7:00
收件人: "Xiang1993/jack-compiler"<jack-compiler@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Xiang1993/jack-compiler] 求帮助,WIN10下jackc main.jack报错main.jack isn't a directory (#12)


 
&mdash;
